version: '3'
services:
  postgres:
    image: postgres:alpine3.19
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: guildedjs
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: guildedjs
    volumes:
      - postgres-vol:/var/lib/postgresql/data

volumes:
  postgres-vol:
