name: Release
on:
    workflow_dispatch:

jobs:
    release:
        name: Release to NPM
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.API_TOKEN_GITHUB }}

            - name: Install PNPM
              uses: pnpm/action-setup@6e1964dde3397a825e79e4607ad57f3f7ca2c7cb
              with:
                  version: 6.32.7

            - name: Set up Node v16
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "pnpm"
                  registry-url: " https://registry.npmjs.org"

            - name: Install dependencies
              run: pnpm install -r

            - name: Build Package
              run: pnpm run build

            - name: Apply version changes to packages
              run: pnpm run changeset:version

            - name: Commit package.json changes
              uses: EndBug/add-and-commit@v9
              with:
                  commit: "--signoff"
                  default_author: github_actor
                  message: "chore: release"
                  push: true

            - name: Release
              run: pnpm recursive publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
